---
- hosts: all
  become: yes
  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Copy the zip file
      ansible.builtin.copy:
        src: sample.zip
        dest: /home/ubuntu/sample.zip

    - name: Unzip the file
      ansible.builtin.unarchive:
        src: /home/ubuntu/sample.zip
        dest: /home/ubuntu/sample
        remote_src: yes

    - name: Remove the zip file
      ansible.builtin.file:
        path: /home/ubuntu/sample.zip
        state: absent

    - name: Install the dependencies
      npm:
        path: /home/ubuntu/sample
        state: present

    - name: Start the application
      command: pm2 start /home/ubuntu/sample/index.js
      args:
        chdir: /home/ubuntu/sample

    - name: Save the process list
      command: pm2 save

    - name: Generate the startup script
      command: pm2 startup
      args:
        platform: systemd
        chdir: /home/ubuntu/sample

